package com.deskera.sdk.common.dto.enums;

public enum DOCUMENT_TYPE {
  QUOTATION,
  PURCHASE_ORDER,
  SALES_ORDER,
  PURCHASE_INVOICE,
  SALES_INVOICE,
  MAKE_PAYMENT,
  RECEIVE_PAYMENT,
  JOURNAL_ENTRY,
  CREDIT_NOTE,
  DEBIT_NOTE,
  EXPENSE,
  EXPENSE_PREPAYMENT,
  DEPOSIT,
  DEPOSIT_ADVPAYMENT
  
}
