package com.deskera.sdk.common.dto.enums;

import java.util.HashMap;
import java.util.Map;

public enum SUPPORTED_COUNTRY {

  AF("AF", "AFN", "Tax", "Afghanistan"),
  AX("AX", "EUR", "Tax", "Åland Islands"),
  AL("AL", "ALL", "Tax", "Albania"),
  DZ("DZ", "DZD", "Tax", "Algeria"),
  AS("AS", "USD", "Tax", "American Samoa"),
  AD("AD", "EUR", "Tax", "Andorra"),
  AO("AO", "AOA", "Tax", "Angola"),
  AI("AI", "XCD", "Tax", "Anguilla"),
  AQ("AQ", "AUD", "Tax", "Antarctica"),
  AG("AG", "XCD", "Tax", "Antigua and Barbuda"),
  AR("AR", "ARS", "Tax", "Argentina"),
  AM("AM", "AMD", "Tax", "Armenia"),
  AW("AW", "AWG", "Tax", "Aruba"),
  AU("AU", "AUD", "Tax", "Australia"),
  AT("AT", "EUR", "Tax", "Austria"),
  AZ("AZ", "AZN", "Tax", "Azerbaijan"),
  BS("BS", "BSD", "Tax", "Bahamas"),
  BH("BH", "BHD", "Tax", "Bahrain"),
  BD("BD", "BDT", "Tax", "Bangladesh"),
  BB("BB", "BBD", "Tax", "Barbados"),
  BY("BY", "BYN", "Tax", "Belarus"),
  BE("BE", "EUR", "Tax", "Belgium"),
  BZ("BZ", "BZD", "Tax", "Belize"),
  BJ("BJ", "XOF", "Tax", "Benin"),
  BM("BM", "BMD", "Tax", "Bermuda"),
  BT("BT", "BTN", "Tax", "Bhutan"),
  BO("BO", "BOB", "Tax", "Bolivia (Plurinational State of)"),
  BQ("BQ", "USD", "Tax", "Bonaire, Sint Eustatius and Saba"),
  BA("BA", "BAM", "Tax", "Bosnia and Herzegovina"),
  BW("BW", "BWP", "Tax", "Botswana"),
  BV("BV", "NOK", "Tax", "Bouvet Island"),
  BR("BR", "BRL", "Tax", "Brazil"),
  IO("IO", "USD", "Tax", "British Indian Ocean Territory"),
  UM("UM", "USD", "Tax", "United States Minor Outlying Islands"),
  VG("VG", "null", "Tax", "Virgin Islands (British)"),
  VI("VI", "USD", "Tax", "Virgin Islands (U.S.)"),
  BN("BN", "BND", "Tax", "Brunei Darussalam"),
  BG("BG", "BGN", "Tax", "Bulgaria"),
  BF("BF", "XOF", "Tax", "Burkina Faso"),
  BI("BI", "BIF", "Tax", "Burundi"),
  KH("KH", "KHR", "Tax", "Cambodia"),
  CM("CM", "XAF", "Tax", "Cameroon"),
  CA("CA", "CAD", "Tax", "Canada"),
  CV("CV", "CVE", "Tax", "Cabo Verde"),
  KY("KY", "KYD", "Tax", "Cayman Islands"),
  CF("CF", "XAF", "Tax", "Central African Republic"),
  TD("TD", "XAF", "Tax", "Chad"),
  CL("CL", "CLP", "Tax", "Chile"),
  CN("CN", "CNY", "Tax", "China"),
  CX("CX", "AUD", "Tax", "Christmas Island"),
  CC("CC", "AUD", "Tax", "Cocos (Keeling) Islands"),
  CO("CO", "COP", "Tax", "Colombia"),
  KM("KM", "KMF", "Tax", "Comoros"),
  CG("CG", "XAF", "Tax", "Congo"),
  CD("CD", "CDF", "Tax", "Congo (Democratic Republic of the)"),
  CK("CK", "NZD", "Tax", "Cook Islands"),
  CR("CR", "CRC", "Tax", "Costa Rica"),
  HR("HR", "HRK", "Tax", "Croatia"),
  CU("CU", "CUC", "Tax", "Cuba"),
  CW("CW", "ANG", "Tax", "Curaçao"),
  CY("CY", "EUR", "Tax", "Cyprus"),
  CZ("CZ", "CZK", "Tax", "Czech Republic"),
  DK("DK", "DKK", "Tax", "Denmark"),
  DJ("DJ", "DJF", "Tax", "Djibouti"),
  DM("DM", "XCD", "Tax", "Dominica"),
  DO("DO", "DOP", "Tax", "Dominican Republic"),
  EC("EC", "USD", "Tax", "Ecuador"),
  EG("EG", "EGP", "Tax", "Egypt"),
  SV("SV", "USD", "Tax", "El Salvador"),
  GQ("GQ", "XAF", "Tax", "Equatorial Guinea"),
  ER("ER", "ERN", "Tax", "Eritrea"),
  EE("EE", "EUR", "Tax", "Estonia"),
  ET("ET", "ETB", "Tax", "Ethiopia"),
  FK("FK", "FKP", "Tax", "Falkland Islands (Malvinas)"),
  FO("FO", "DKK", "Tax", "Faroe Islands"),
  FJ("FJ", "FJD", "Tax", "Fiji"),
  FI("FI", "EUR", "Tax", "Finland"),
  FR("FR", "EUR", "Tax", "France"),
  GF("GF", "EUR", "Tax", "French Guiana"),
  PF("PF", "XPF", "Tax", "French Polynesia"),
  TF("TF", "EUR", "Tax", "French Southern Territories"),
  GA("GA", "XAF", "Tax", "Gabon"),
  GM("GM", "GMD", "Tax", "Gambia"),
  GE("GE", "GEL", "Tax", "Georgia"),
  DE("DE", "EUR", "Tax", "Germany"),
  GH("GH", "GHS", "Tax", "Ghana"),
  GI("GI", "GIP", "Tax", "Gibraltar"),
  GR("GR", "EUR", "Tax", "Greece"),
  GL("GL", "DKK", "Tax", "Greenland"),
  GD("GD", "XCD", "Tax", "Grenada"),
  GP("GP", "EUR", "Tax", "Guadeloupe"),
  GU("GU", "USD", "Tax", "Guam"),
  GT("GT", "GTQ", "Tax", "Guatemala"),
  GG("GG", "GBP", "Tax", "Guernsey"),
  GN("GN", "GNF", "Tax", "Guinea"),
  GW("GW", "XOF", "Tax", "Guinea-Bissau"),
  GY("GY", "GYD", "Tax", "Guyana"),
  HT("HT", "HTG", "Tax", "Haiti"),
  HM("HM", "AUD", "Tax", "Heard Island and McDonald Islands"),
  VA("VA", "EUR", "Tax", "Holy See"),
  HN("HN", "HNL", "Tax", "Honduras"),
  HK("HK", "HKD", "Tax", "Hong Kong"),
  HU("HU", "HUF", "Tax", "Hungary"),
  IS("IS", "ISK", "Tax", "Iceland"),
  IN("IN", "INR", "Tax", "India"),
  ID("ID", "IDR", "Tax", "Indonesia"),
  CI("CI", "XOF", "Tax", "Côte d'Ivoire"),
  IR("IR", "IRR", "Tax", "Iran (Islamic Republic of)"),
  IQ("IQ", "IQD", "Tax", "Iraq"),
  IE("IE", "EUR", "Tax", "Ireland"),
  IM("IM", "GBP", "Tax", "Isle of Man"),
  IL("IL", "ILS", "Tax", "Israel"),
  IT("IT", "EUR", "Tax", "Italy"),
  JM("JM", "JMD", "Tax", "Jamaica"),
  JP("JP", "JPY", "Tax", "Japan"),
  JE("JE", "GBP", "Tax", "Jersey"),
  JO("JO", "JOD", "Tax", "Jordan"),
  KZ("KZ", "KZT", "Tax", "Kazakhstan"),
  KE("KE", "KES", "Tax", "Kenya"),
  KI("KI", "AUD", "Tax", "Kiribati"),
  KW("KW", "KWD", "Tax", "Kuwait"),
  KG("KG", "KGS", "Tax", "Kyrgyzstan"),
  LA("LA", "LAK", "Tax", "Lao People's Democratic Republic"),
  LV("LV", "EUR", "Tax", "Latvia"),
  LB("LB", "LBP", "Tax", "Lebanon"),
  LS("LS", "LSL", "Tax", "Lesotho"),
  LR("LR", "LRD", "Tax", "Liberia"),
  LY("LY", "LYD", "Tax", "Libya"),
  LI("LI", "CHF", "Tax", "Liechtenstein"),
  LT("LT", "EUR", "Tax", "Lithuania"),
  LU("LU", "EUR", "Tax", "Luxembourg"),
  MO("MO", "MOP", "Tax", "Macao"),
  MK("MK", "MKD", "Tax", "Macedonia (the former Yugoslav Republic of)"),
  MG("MG", "MGA", "Tax", "Madagascar"),
  MW("MW", "MWK", "Tax", "Malawi"),
  MY("MY", "MYR", "Tax", "Malaysia"),
  MV("MV", "MVR", "Tax", "Maldives"),
  ML("ML", "XOF", "Tax", "Mali"),
  MT("MT", "EUR", "Tax", "Malta"),
  MH("MH", "USD", "Tax", "Marshall Islands"),
  MQ("MQ", "EUR", "Tax", "Martinique"),
  MR("MR", "MRO", "Tax", "Mauritania"),
  MU("MU", "MUR", "Tax", "Mauritius"),
  YT("YT", "EUR", "Tax", "Mayotte"),
  MX("MX", "MXN", "Tax", "Mexico"),
  FM("FM", "null", "Tax", "Micronesia (Federated States of)"),
  MD("MD", "MDL", "Tax", "Moldova (Republic of)"),
  MC("MC", "EUR", "Tax", "Monaco"),
  MN("MN", "MNT", "Tax", "Mongolia"),
  ME("ME", "EUR", "Tax", "Montenegro"),
  MS("MS", "XCD", "Tax", "Montserrat"),
  MA("MA", "MAD", "Tax", "Morocco"),
  MZ("MZ", "MZN", "Tax", "Mozambique"),
  MM("MM", "MMK", "Tax", "Myanmar"),
  NA("NA", "NAD", "Tax", "Namibia"),
  NR("NR", "AUD", "Tax", "Nauru"),
  NP("NP", "NPR", "Tax", "Nepal"),
  NL("NL", "EUR", "Tax", "Netherlands"),
  NC("NC", "XPF", "Tax", "New Caledonia"),
  NZ("NZ", "NZD", "Tax", "New Zealand"),
  NI("NI", "NIO", "Tax", "Nicaragua"),
  NE("NE", "XOF", "Tax", "Niger"),
  NG("NG", "NGN", "Tax", "Nigeria"),
  NU("NU", "NZD", "Tax", "Niue"),
  NF("NF", "AUD", "Tax", "Norfolk Island"),
  KP("KP", "KPW", "Tax", "Korea (Democratic People's Republic of)"),
  MP("MP", "USD", "Tax", "Northern Mariana Islands"),
  NO("NO", "NOK", "Tax", "Norway"),
  OM("OM", "OMR", "Tax", "Oman"),
  PK("PK", "PKR", "Tax", "Pakistan"),
  PW("PW", "(none)", "Tax", "Palau"),
  PS("PS", "ILS", "Tax", "Palestine, State of"),
  PA("PA", "PAB", "Tax", "Panama"),
  PG("PG", "PGK", "Tax", "Papua New Guinea"),
  PY("PY", "PYG", "Tax", "Paraguay"),
  PE("PE", "PEN", "Tax", "Peru"),
  PH("PH", "PHP", "Tax", "Philippines"),
  PN("PN", "NZD", "Tax", "Pitcairn"),
  PL("PL", "PLN", "Tax", "Poland"),
  PT("PT", "EUR", "Tax", "Portugal"),
  PR("PR", "USD", "Tax", "Puerto Rico"),
  QA("QA", "QAR", "Tax", "Qatar"),
  XK("XK", "EUR", "Tax", "Republic of Kosovo"),
  RE("RE", "EUR", "Tax", "Réunion"),
  RO("RO", "RON", "Tax", "Romania"),
  RU("RU", "RUB", "Tax", "Russian Federation"),
  RW("RW", "RWF", "Tax", "Rwanda"),
  BL("BL", "EUR", "Tax", "Saint Barthélemy"),
  SH("SH", "SHP", "Tax", "Saint Helena, Ascension and Tristan da Cunha"),
  KN("KN", "XCD", "Tax", "Saint Kitts and Nevis"),
  LC("LC", "XCD", "Tax", "Saint Lucia"),
  MF("MF", "EUR", "Tax", "Saint Martin (French part)"),
  PM("PM", "EUR", "Tax", "Saint Pierre and Miquelon"),
  VC("VC", "XCD", "Tax", "Saint Vincent and the Grenadines"),
  WS("WS", "WST", "Tax", "Samoa"),
  SM("SM", "EUR", "Tax", "San Marino"),
  ST("ST", "STD", "Tax", "Sao Tome and Principe"),
  SA("SA", "SAR", "Tax", "Saudi Arabia"),
  SN("SN", "XOF", "Tax", "Senegal"),
  RS("RS", "RSD", "Tax", "Serbia"),
  SC("SC", "SCR", "Tax", "Seychelles"),
  SL("SL", "SLL", "Tax", "Sierra Leone"),
  SG("SG", "SGD", "GST", "Singapore"),
  SX("SX", "ANG", "Tax", "Sint Maarten (DGMTh part)"),
  SK("SK", "EUR", "Tax", "Slovakia"),
  SI("SI", "EUR", "Tax", "Slovenia"),
  SB("SB", "SBD", "Tax", "Solomon Islands"),
  SO("SO", "SOS", "Tax", "Somalia"),
  ZA("ZA", "ZAR", "Tax", "South Africa"),
  GS("GS", "GBP", "Tax", "South Georgia and the South Sandwich Islands"),
  KR("KR", "KRW", "Tax", "Korea (Republic of)"),
  SS("SS", "SSP", "Tax", "South Sudan"),
  ES("ES", "EUR", "Tax", "Spain"),
  LK("LK", "LKR", "Tax", "Sri Lanka"),
  SD("SD", "SDG", "Tax", "Sudan"),
  SR("SR", "SRD", "Tax", "Suriname"),
  SJ("SJ", "NOK", "Tax", "Svalbard and Jan Mayen"),
  SZ("SZ", "SZL", "Tax", "Swaziland"),
  SE("SE", "SEK", "Tax", "Sweden"),
  CH("CH", "CHF", "Tax", "Switzerland"),
  SY("SY", "SYP", "Tax", "Syrian Arab Republic"),
  TW("TW", "TWD", "Tax", "Taiwan"),
  TJ("TJ", "TJS", "Tax", "Tajikistan"),
  TZ("TZ", "TZS", "Tax", "Tanzania, United Republic of"),
  TH("TH", "THB", "Tax", "Thailand"),
  TL("TL", "USD", "Tax", "Timor-Leste"),
  TG("TG", "XOF", "Tax", "Togo"),
  TK("TK", "NZD", "Tax", "Tokelau"),
  TO("TO", "TOP", "Tax", "Tonga"),
  TT("TT", "TTD", "Tax", "Trinidad and Tobago"),
  TN("TN", "TND", "Tax", "Tunisia"),
  TR("TR", "TRY", "Tax", "Turkey"),
  TM("TM", "TMT", "Tax", "Turkmenistan"),
  TC("TC", "USD", "Tax", "Turks and Caicos Islands"),
  TV("TV", "AUD", "Tax", "Tuvalu"),
  UG("UG", "UGX", "Tax", "Uganda"),
  UA("UA", "UAH", "Tax", "Ukraine"),
  AE("AE", "AED", "Tax", "United Arab Emirates"),
  GB("GB", "GBP", "Tax", "United Kingdom of Great Britain and Northern Ireland"),
  US("US", "USD", "Sales Tax", "United States of America"),
  US1("US1", "USD", "Tax", "United States of America"),
  UY("UY", "UYU", "Tax", "Uruguay"),
  UZ("UZ", "UZS", "Tax", "Uzbekistan"),
  VU("VU", "VUV", "Tax", "Vanuatu"),
  VE("VE", "VEF", "Tax", "Venezuela (Bolivarian Republic of)"),
  VN("VN", "VND", "Tax", "Viet Nam"),
  WF("WF", "XPF", "Tax", "Wallis and Futuna"),
  EH("EH", "MAD", "Tax", "Western Sahara"),
  YE("YE", "YER", "Tax", "Yemen"),
  ZM("ZM", "ZMW", "Tax", "Zambia"),
  ZW("ZW", "BWP", "Tax", "Zimbabwe");

  private String abbreviation;
  private String currency;
  private String defaultTax;
  private String countryName;

  private static final Map<String, SUPPORTED_COUNTRY> lookup = new HashMap<String, SUPPORTED_COUNTRY>();


  static {
    for (SUPPORTED_COUNTRY d : SUPPORTED_COUNTRY.values()) {
      lookup.put(d.getAbbreviation(), d);
    }
  }

  SUPPORTED_COUNTRY(final String abbreviation, final String currency, final String defaultTax,
      final String countryName) {
    this.abbreviation = abbreviation;
    this.currency = currency;
    this.defaultTax = defaultTax;
    this.countryName = countryName;
  }

  public String getAbbreviation() {
    return abbreviation;
  }

  public String getCurrency() {
    return currency;
  }

  public String getDefaultTax() {
    return defaultTax;
  }

  public String getCountryName() {
    return countryName;
  }

  public static SUPPORTED_COUNTRY get(String abbreviation) {
    return lookup.get(abbreviation);
  }
}

